language: python
python:
  - "2.7"
services:
  - couchdb
install:
  - source cfg4dev
  - pip install coveralls
script:
  - pep8
  - flake8
  - python setup.py sdist --formats=gztar
  - nosetests --with-coverage --cover-branches --cover-erase --cover-package tor_async_couchdb
  - pip install -r samples/requirements.txt
  - samples/test_all_samples.sh
after_success:
  - coveralls || true
