language: python
python:
  - "2.7"
sudo: required
services:
  - couchdb
install:
  # couchdb seems to take a bit to get started on travis
  # the until loop makes sure couchdb is running before
  # cfg4dev is sourced and the curl after the until loop
  # gives us couchdb version info
  - until curl http://127.0.0.1:5984 >& /dev/null; do echo "waiting for couchdb to start" && sleep 1; done && curl http://127.0.0.1:5984
  - source cfg4dev
  - pip install coveralls
  - pip install -r samples/requirements.txt
  # need pandoc installed because it's not provisioned
  # by default and we want to use it below
  - sudo apt-get install -y pandoc
script:
  - pycodestyle
  - flake8
  - travis_fold start "build.python.packages"
  - pandoc README.md -o README.rst
  - python setup.py sdist --formats=gztar
  - travis_fold end "build.python.packages"
  - nosetests --with-coverage --cover-branches --cover-erase --cover-package tor_async_couchdb
  - samples/test_all_samples.sh
after_success:
  - coveralls || true
