language: python
python:
  - "2.7"
sudo: required
install:
  - source cfg4dev
  - pip install coveralls
  - docker pull koalaman/shellcheck:latest
  ##### need pandoc installed because it's not provisioned
  ##### by default and we want to use it below
  ##### - sudo apt-get install -y pandoc
script:
  - run_pip_check.sh
  - run_flake8.sh
  ##### - run_shellcheck.sh -v
  ##### - travis_fold start "build.python.packages"
  ##### - pandoc README.md -o README.rst
  ##### - python setup.py sdist --formats=gztar
  ##### - travis_fold end "build.python.packages"
  - run_unit_tests.sh
  ##### - samples/test_all_samples.sh
after_success:
  - coveralls || true
