FROM simonsdave/xenial-dev-env:%DEV_ENV_VERSION%

MAINTAINER Dave Simons

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get install -y build-essential
RUN apt-get install -y libffi-dev
RUN apt-get install -y python-crypto
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y libssl-dev

COPY requirements.txt /tmp/requirements.txt
COPY setup.py /tmp/setup.py
RUN mkdir /tmp/tor_async_couchdb
COPY tor_async_couchdb/__init__.py /tmp/tor_async_couchdb/__init__.py
RUN mkdir /tmp/samples
COPY samples/requirements.txt /tmp/samples/requirements.txt

RUN cd /tmp && \
    pip install --requirement "/tmp/requirements.txt" && \
    pip install --requirement "/tmp/samples/requirements.txt"

RUN rm "/tmp/setup.py" && \
    rm "/tmp/requirements.txt" && \
    rm -r "/tmp/tor_async_couchdb" && \
    rm -r "/tmp/tor_async_couchdb.egg-info" && \
    rm "/tmp/samples/requirements.txt" && \
    rm -r "/tmp/samples"

ENV DEBIAN_FRONTEND newt

ENV PYTHONPATH /app

WORKDIR /app
